#!/bin/bash

#SBATCH --job-name=teamxmidtermtraining
#SBATCH -e ../logs/condatest.e%A
#SBATCH -o ../logs/condatest.o%A
#SBATCH --partition=standard
#SBATCH --ntasks=1
#SBATCH --time=1:10:00
#SBATCH --account=lyons-lab
#SBATCH --cpus-per-task=1
#SBATCH --mem=4GB
#SBATCH --gres=gpu:1



# other common options. 
### means they are commented out
###SBATCH --mem-per-cpu=5gb
###SBATCH --partition=windfall
###SBATCH --gres=gpu:1
###SBATCH --cpus-per-task=4 

###SBATCH --mail-type=ALL
###SBATCH --mail-user=netid@email.arizona.edu


echo 'This script is running on:'
hostname
echo $SHELL
###conda init bash
source ~/.bash_profile

conda activate info529midterm
echo 'Finished model training'
